package com.rundong;

import io.quarkus.runtime.annotations.RegisterForReflection;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.time.LocalDateTime;

@RegisterForReflection
@DynamoDbBean
public class Post {

    private String postId;

    private String userId;

    private String title;

    private String content;

    private String contactInfo;

    private String picUrls;

    private String countryCode;

    private String stateCode;

    private String cityCode;

    /**
     * optional, can be something like Allston, downtown
     */
    private String area;

    private LocalDateTime createTime;

    private LocalDateTime updateTime;

    /**
     * 0: active, 1: deleted
     */
    private Integer deleteFlag;

    @DynamoDbPartitionKey
    @DynamoDbAttribute(PostService.POST_ID_COL)
    @DynamoDbAutoGeneratedUuid
    public String getPostId() {
        return postId;
    }

    @DynamoDbAttribute(PostService.POST_USER_ID)
    public String getUserId() {
        return userId;
    }

    @DynamoDbAttribute(PostService.POST_TITLE)
    public String getTitle() {
        return title;
    }

    public String getContent() {
        return content;
    }

    public String getContactInfo() {
        return contactInfo;
    }

    public String getPicUrls() {
        return picUrls;
    }

    public String getCountryCode() {
        return countryCode;
    }

    public String getStateCode() {
        return stateCode;
    }

    public String getCityCode() {
        return cityCode;
    }

    public String getArea() {
        return area;
    }

    public LocalDateTime getCreateTime() {
        return createTime;
    }

    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    public Integer getDeleteFlag() {
        return deleteFlag;
    }

//    @DynamoDbAutoGeneratedUuid
    public void setPostId(String postId) {
        this.postId = postId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public void setContactInfo(String contactInfo) {
        this.contactInfo = contactInfo;
    }

    public void setPicUrls(String picUrls) {
        this.picUrls = picUrls;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }

    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}
